/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.cantineplanner.codegen.tables.records;


import de.htwsaar.cantineplanner.codegen.tables.Review;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>review.rating_id</code>.
     */
    public void setRatingId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>review.rating_id</code>.
     */
    public Integer getRatingId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>review.meal_id</code>.
     */
    public void setMealId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>review.meal_id</code>.
     */
    public Integer getMealId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>review.rating</code>.
     */
    public void setRating(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>review.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>review.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>review.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>review.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>review.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(Integer ratingId, Integer mealId, Integer rating, String comment, LocalDateTime createdAt) {
        super(Review.REVIEW);

        setRatingId(ratingId);
        setMealId(mealId);
        setRating(rating);
        setComment(comment);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
