/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.cantineplanner.codegen;


import de.htwsaar.cantineplanner.codegen.tables.Meals;
import de.htwsaar.cantineplanner.codegen.tables.Review;
import de.htwsaar.cantineplanner.codegen.tables.Users;
import de.htwsaar.cantineplanner.codegen.tables.records.MealsRecord;
import de.htwsaar.cantineplanner.codegen.tables.records.ReviewRecord;
import de.htwsaar.cantineplanner.codegen.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MealsRecord> MEALS__PK_MEALS = Internal.createUniqueKey(Meals.MEALS, DSL.name("pk_meals"), new TableField[] { Meals.MEALS.MEAL_ID }, true);
    public static final UniqueKey<ReviewRecord> REVIEW__PK_REVIEW = Internal.createUniqueKey(Review.REVIEW, DSL.name("pk_review"), new TableField[] { Review.REVIEW.RATING_ID }, true);
    public static final UniqueKey<UsersRecord> USERS__PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.USERID }, true);
    public static final UniqueKey<UsersRecord> USERS__UK_USERS_1_15067867 = Internal.createUniqueKey(Users.USERS, DSL.name("uk_users_1_15067867"), new TableField[] { Users.USERS.EMAIL }, true);
}
