/*
 * This file is generated by jOOQ.
 */
package de.htwsaar.cantineplanner.codegen;


import de.htwsaar.cantineplanner.codegen.tables.Meals;
import de.htwsaar.cantineplanner.codegen.tables.Review;
import de.htwsaar.cantineplanner.codegen.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>meals</code>.
     */
    public static final Meals MEALS = Meals.MEALS;

    /**
     * The table <code>review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
